### ISSUE TITLE
无法正常启动客户端

### ISSUE THREAD

**Issue by Yuyue112** [BrokenDawn627/Infinity-Modpack#22]
当启动时弹出
Uncaught exception in thread "main"
java.lang.RuntimeException: error remapping game jars [C:\Users\Administrator\Desktop\.minecraft\versions\Infinity - Fabric\Infinity - Fabric.jar]
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:219)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.initialize(MinecraftGameProvider.java:281)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:136)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.io.IOException: the jar file C:\Users\Administrator\Desktop\.minecraft\versions\Infinity - Fabric\.fabric\remappedJars\minecraft-1.18.1-0.13.3\client-intermediary.jar.tmp can't be written
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:114)
	at net.fabricmc.tinyremapper.OutputConsumerPath.<init>(OutputConsumerPath.java:47)
	at net.fabricmc.tinyremapper.OutputConsumerPath$Builder.build(OutputConsumerPath.java:76)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate0(GameProviderHelper.java:273)
	at net.fabricmc.loader.impl.game.GameProviderHelper.deobfuscate(GameProviderHelper.java:217)
	... 4 more
[错误报告-2022-5-10_14.59.29.zip](https://github.com/BrokenDawn627/Infinity-Modpack/files/8659021/-2022-5-10_14.59.29.zip)

**Comment by BrokenDawn627** [comment]
不接受一切下载安装启动问题 请检查java版本与分配内存空间 是否开启版本隔离
