### ISSUE TITLE
对服务端硬件有什么要求吗..4核8g内存的腾讯云不到一天崩了11次..

### ISSUE THREAD

**Issue by FireworksZhang** [BrokenDawn627/Infinity-Modpack#30]
[crash-2022-06-01_00.33.00-server.txt](https://github.com/BrokenDawn627/Infinity-Modpack/files/8813098/crash-2022-06-01_00.33.00-server.txt)
错误日志在这里..

**Comment by FireworksZhang** [comment]
大部分的错误信息都是下面这样的：
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$$0" is null
	at net.minecraft.class_2519.method_23256(class_2519.java:71)
	at net.minecraft.class_2487.method_10582(class_2487.java:231)
	at com.github.clevernucleus.opc.impl.PlayerCacheImpl.toNbt(PlayerCacheImpl.java:150)
	at net.minecraft.class_31.handler$cjp000$onUpdateProperties(class_31.java:697)
	at net.minecraft.class_31.method_158(class_31.java)
	at net.minecraft.class_31.method_163(class_31.java:231)
	at net.minecraft.class_32$class_5143.method_27426(class_32.java:340)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:568)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by chuangyuan1** [comment]
https://github.com/CleverNucleus/playerex/issues/50

没办法这个是playerex模组报错 这个模组的作用是提供物品栏的属性加点
你只要关闭了服务端的正版验证玩一段时间就会出现错误
要不就开启正版验证 所有人都用正版玩 要不就只能给这个模组删掉
模组作者在1.18.2之后的版本当中修复了这个问题 没给1.18.1修
