### ISSUE TITLE
搭建好服务器进入之后客户端崩溃

### ISSUE THREAD

**Issue by unclexii** [BrokenDawn627/Infinity-Modpack#35]
---- Minecraft Crash Report ----
// My bad.

Time: 6/13/22, 4:24 AM
Description: Unexpected error

java.lang.NullPointerException: **Cannot read field "field_13073" because "$$0" is null**
	at net.minecraft.class_2874.method_31108(class_2874.java:350)
	at net.id.aether.util.RegistryUtil.dimensionMatches(RegistryUtil.java:14)
	at net.minecraft.class_758.redirect$fje000$adjustVoidVector(class_758.java:3034)
	at net.minecraft.class_758.method_3210(class_758.java:143)
	at net.minecraft.class_761.method_22710(class_761.java:1238)
	at net.minecraft.class_757.method_3188(class_757.java:1031)
	at net.minecraft.class_757.method_3192(class_757.java:811)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by LuLuLuOfficial** [comment]
一样问题，只能用服务端整合包的bat开服，面板和开服器都不行，有解吗？
