### ISSUE TITLE
局域网联机崩溃，我朋友是离线联机的，初步判断是playerE里的OfflinePlayerCacheProvider.java中函数isEmpty()的引用错误

### ISSUE THREAD

**Issue by noonbamboo** [BrokenDawn627/Infinity-Modpack#39]
---- Minecraft Crash Report ----
// There are four lights!

Time: 6/20/22, 10:15 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "$$0" is null
	at net.minecraft.class_2519.method_23256(class_2519.java:71)
	at net.minecraft.class_2487.method_10582(class_2487.java:231)
	at com.github.clevernucleus.opc.impl.PlayerCacheImpl.toNbt(PlayerCacheImpl.java:150)
	at net.minecraft.class_31.handler$egf000$onUpdateProperties(class_31.java:697)
	at net.minecraft.class_31.method_158(class_31.java)
	at net.minecraft.class_31.method_163(class_31.java:231)
	at net.minecraft.class_32$class_5143.method_27426(class_32.java:340)
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:568)
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:585)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:848)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3890308848 bytes (3710 MiB) / 9663676416 bytes (9216 MiB) up to 9663676416 bytes (9216 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.99
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f99
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1165
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25751.80
	Virtual memory used (MB): 21527.21
	Swap memory total (MB): 10010.48
	Swap memory used (MB): 1052.73
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx9216m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.4.9
		alloy_forgery: Alloy Forgery 2.0.9+1.18
		amethystequipment: Amethyst Equipment 1.18.1
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		anvil_fix: AnvilFix development+custom-1.18
		appleskin: AppleSkin 2.3.0+mc1.18.1
		arcanus: Arcanus 1.27
		architectury: Architectury 3.9.55
		awesomedungeon: Awesome Dungeon 2.0.8
		awesomedungeonend: Awesome Dungeon Edition end 1.0.0
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.1
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.6
		balm-fabric: Balm 2.4.3+0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bclib: BCLib 1.3.5
		betterend: Better End 1.0.3
		betterf3: BetterF3 1.2.2
		betternether: Better Nether 6.0.12
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		betterthirdperson: Better Third Person 1.6.0
		blur: Blur (Fabric) 2.4.1
		bobby: Bobby 3.1.0
		boneequipment: Bone Equipment 1.18.1
		bookshelf: Bookshelf 12.0.23
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.5-1.18
		botania: Botania 1.18.1-429-FABRIC
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-world: Cardinal Components API (worlds) 4.0.0
		carrier: Carrier 1.9.1
		cavetweaks: Cave Tweaks 1.0
		chat_heads: Chat Heads 0.6.0
		cleancut: CleanCut 1.18-4.0-fabric
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.62
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		companion: Companion 1.2.1
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		controlling: Controlling For Fabric 9.0+15
		copperequipment: Copper Equipment fabric-1.18.1-v2.0.0
		crafttweaker: CraftTweaker 9.0.81
		crawl: Crawl 0.10.2
		creeperoverhaul: Creeper Overhaul 0.3.0
		crosshairmod: Crosshair Mod 0.4.3
		crowdin-translate: CrowdinTranslate 1.4+1.18
		customportalapi: Custom Portal Api 0.0.1-beta49-1.18
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		dataattributes: Data Attributes 1.1.5
		defaultoptions: Default Options 14.1.0
		dehydration: Dehydration 1.2.7
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		doublejump: Double Jump Mod 1.0.1+mc1.18
		dragonloot: DragonLoot 1.0.10
		drippyloadingscreen: Drippy Loading Screen 1.5.1
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49d-fabric
		dusk: Dusk Mod 1.18.2-1.9
		dynamicfps: Dynamic FPS 2.1.0
		edenring: EdenRing 0.3.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		emeraldequipment: Emerald Equipment 1.18.1
		enchantedbookredesign: Enchanted Book Redesign 1.17.1-2.0
		enchantment_force: enchantment_force 0.1.7
		enchdesc: EnchantmentDescriptions 9.0.13
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		enhancedcelestials: Enhanced Celestials 2.0.6
		entityculling: EntityCulling-Fabric 1.5.1
		environmentz: EnvironmentZ 1.2.1
		experiencebugfix: Experience Bug Fix 18
		extended_armor_bars: Extended Armor Bars 1.1.0
		extraalchemy: Extra Alchemy 1.7.0
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-furnaces: Fabric Furnaces 2.1.0-1.18.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricenchantments: Fabric Enchantments 0.7.1
		fabricloader: Fabric Loader 0.13.3
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		fancymenu: FancyMenu 2.7.0
		farsighted-mobs: Farsighted Mobs 1.1-1.18
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		flintytools: Flinty Tools 1.1.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		gateofbabylon: Gate Of Babylon 1.6.0-1.18.1
		geckolib3: Geckolib 3.0.33
		gobber2: Gobber2 2.5.63.3
		graveyard: The Graveyard 1.6
		greater_eye: Greater Eye of Ender 1.3.21
		gud_recipe_confidence: Recipe Confidence 1.0.2
		heartytrinkets: Hearty Trinkets 1.18.1-1.0.0
		highlighter: Highlighter 1.1.2
		hitmarker: HitMarker 1.0a-1.16.2
		hookshot: Hookshot 24.0
		hoverpets: Hover Pets 0.2.0
		iceberg: Iceberg 1.0.38
		impaled: Impaled 1.0.3
		imperishableitems: Imperishable Items 2.1.2
		incantationem: Incantationem 1.1.3+1.18.1
		incubus_core: Incubus Core 1.6.6+1.18.1
		indium: Indium 1.0.2-alpha3+mc1.18.1
		infusion_table: Infusion Table 1.0.5
		ingredient-extension-api: Ingredient Extension API 2.0.1
		inmis: Inmis 2.5.1-1.18.1
		interactic: Interactic 0.1.8+1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.3.6
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.0-pre
		itemborders: Item Borders 1.1.5
		itemmodelfix: Item Model Fix 1.0.3+1.18
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		keybindsgalore: Keybinds Galore 1.0+1.18
		kjsextras: KubeJS Extras 1.5.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
		kubejs: KubeJS 1801.4.3-build.310
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lanserverproperties: Lan Server Properties 1.7
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		libraryferret: Library Ferret 1.0.3
		libzoomer: LibZoomer 0.3.0+1.17.1
		loadmyresources: Load My Resources 1.0.1
		lychee: Lychee Tweaker 1.5.1
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magiccombatwands: Magic Combat Wands 1.0.1
		magna: Magna 1.7.0-1.18-pre1
		mcda: MC Dungeons Armors 2.0.6
		mcdar: MC Dungeons Artifacts 1.4.8
		mcdw: MC Dungeons Weapons 4.3.2
		megaparrot: Megaparrot 1.0.3
		mesh: Mesh 0.19.0-alpha
		mesh_api: Mesh API 0.19.0-alpha
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		minieffects: Mini Effects 4.0.0
		mm: Manningham Mills 2.3
		mobz: MobZ 3.3.1
		modmenu: Mod Menu 3.0.1
		morebannerfeatures: More Banner Features 1.1.3
		moretags: More Tags 2.0.2
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.1+1.18.1
		mousetweaks: Mouse Tweaks 2.22
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		mythicmetals: Mythic Metals 0.12.2
		mythicmounts: Mythic Mounts 1.18.1-7.0
		net_objecthunter_exp4j: exp4j 0.4.8
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		numismatic-overhaul: Numismatic Overhaul 0.1.8+1.18
		nyfsquiver: Nyf's Quivers Fabric-0.4.0-1.18
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.1-1.18.1
		opc: Offline Player Cache 0.0.1
		openloader: OpenLoader 11.0.4
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_javassist_javassist: javassist 3.28.0-GA
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		org_reflections_reflections: reflections 0.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		oro_config: OroArmor Config 2.1.0
		owo: oωo 0.5.2+1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.3.0+1.14.4-1.19
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		playerex: PlayerEx 3.1.4
		polymorph: Polymorph 0.0.20-1.18.2
		pride: Pride Lib 1.1.0+1.17
		pugh_lib: Pugh Lib 1.2.15
		pugh_tools: Pugh Tools 1.1.22
		puzzleslib: Puzzles Lib 3.2.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.0
		reinfbarrel: Reinforced Barrels 2.0.0+1.18
		reinfchest: Reinforced Chests 2.0.0+1.18
		reinfcore: Reinforced Core 2.0.0+1.18
		reinfshulker: Reinforced Shulker Boxes 2.0.0+1.18
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		reroll: Reroll 1.4.0-1.18.1
		rhino: Rhino 1801.1.9-build.135
		ringsofascension: Rings of Ascension 1.0
		roughlyenoughitems: Roughly Enough Items 7.4.456
		roughlyenoughresources: Roughly Enough Resources 2.4.1
		runelic: Runelic 10.0.6
		satin: Satin 1.7.2
		sculk_worm: Sculk Worm 0.1.5
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha6+build.14
		sodium-extra: Sodium Extra 0.3.9
		spruceui: SpruceUI 3.3.0+1.17
		stacc: Stacc 1.3.0
		starlight: Starlight 1.0.0+fabric.d0a3220
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.4.2
		tellme: TellMe 0.9.0
		the_aether: Paradise Lost 1.6.9+1.18.1
		things: Things 0.2.15+1.18
		tinyskeletons: Tiny Skeletons 3.1.0
		toolstats: ToolStats 8.0.6
		tooltipfix: ToolTip Fix 1.0.4-1.18
		torchbowmod: TorchBowMod 1.0
		torohealth: ToroHealth Damage Indicators 1.18-fabric-2
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.2.0
		tradingpost: Trading Post 3.1.2
		trashslot: TrashSlot 11.0.2
		travelersbackpack: Traveler's Backpack 1.18.1-7.0.0
		treeaxe: The TreeAxe 1.1.32.3
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		trulytreasures: Truly Treasures fabric-1.18.1-2.0.1
		victus: Victus 0.1.7+1.18
		voidtotem: VoidTotem (Fabric) 1.18.1-1.2.0
		voidz: VoidZ 1.0.5
		waystones: Waystones 9.0.4
		wmitaf: WMITAF 2.2.0
		x-enchant: X-Enchant 1.18-8.6
		xp_storage: XP Storage 1.4.3+1.18
		xtraarrows: Xtra Arrows 1.8.1
		yigd: You're in Grave Danger 1.2.25
		yungsapi: YUNG's API 1.18-Fabric-36
		zombified: Zombified 1.3.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['Noonbamboo'/197, l='ServerLevel[新的世界]', x=-121.09, y=62.00, z=-169.63]]
	Data Packs: vanilla, loadmyresources.hiddenpack, Fabric Mods, data/Infinity-Datapack-CN.zip, data/Repurposed_Structures-More_Villagers_v4.zip
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by EnterFor** [comment]
同样的问题，暂时歇逼，只能先单机了

**Comment by yanlingww** [comment]
我也是，我关掉这个mod联机情况稳定很多

**Comment by BrokenDawn627** [comment]
https://github.com/CleverNucleus/PlayerEx/issues/50
